/**
 * OpenCode Zen adapter for the DeepSeek Harness LLM seam.
 *
 * Registers the `opencode-zen` provider route and impersonates the OpenCode
 * CLI client on the wire: User-Agent, `x-opencode-*` headers and their
 * `ses_`/`msg_` id scheme are generated byte-identically to
 * https://github.com/anomalyco/opencode (`packages/opencode/src/id/id.ts`
 * `create()` and `packages/opencode/src/session/llm/request.ts`), and the
 * model catalog is resolved at runtime from the Zen models endpoint instead of
 * being hard-coded. Request-body serialization and SSE decoding are reused
 * from `@deepseek-ai/dsh-llm-deepseek` (patched to export them), so no wire
 * format logic is duplicated here.
 *
 * TLS: the OpenCode CLI runs on Bun (BoringSSL); this adapter runs under
 * Node/OpenSSL. The nix package ships an `--openssl-config` that aligns the
 * cipher-suite order with the observed BoringSSL ClientHello, but the
 * extension order is OpenSSL-determined, so the JA3/JA4 values are NOT
 * byte-identical. This is a known, documented limitation.
 *
 * @module dsh-llm-opencode-zen
 */

import { randomBytes } from "node:crypto";
import type { Context } from "@deepseek-ai/cordis";
import type { CredentialRef } from "@deepseek-ai/dsh-credentials";
import {
  attributionHeaders,
  type GenerateOptions,
  isContextWindowExceededError,
  isQuotaExceededError,
  LlmAdapter,
  LlmError,
  type LlmModelInfo,
  type LlmProviderInfo,
  type LlmResolvedModelInfo,
  QUOTA_EXCEEDED_CODE,
  ReasoningEffortId,
  type StreamChunk,
} from "@deepseek-ai/dsh-llm";
import {
  parseSse,
  type RequestDefaults,
  serializeRequest,
  translate,
} from "@deepseek-ai/dsh-llm-deepseek";
import { idleWatchdog, timeoutOf } from "@deepseek-ai/dsh-timeout";
import z from "@deepseek-ai/schemastery";

export const name = "llm-opencode-zen";
export const inject = ["llm"];

/** The single provider route this plugin owns. */
const PROVIDER = "opencode-zen";
const PUBLIC_BASE_URL = "https://opencode.ai/zen/v1";
const DEFAULT_API_KEY_ENV = "OPENCODE_API_KEY";
/** Zen's public default credential, matching the OpenCode CLI behavior. */
const PUBLIC_KEY = "public";
const DEFAULT_MODEL = "deepseek-v4-flash-free";
const DEFAULT_CONTEXT_WINDOW = 1_000_000;
const DEFAULT_MAX_TOKENS = 256_000;
const DEFAULT_STREAM_IDLE_TIMEOUT_MS = 300_000;
const STREAM_IDLE_TIMEOUT_CODE = "LLM_STREAM_IDLE_TIMEOUT";
const REQUEST_TIMEOUT_MS = 30_000;

// -- OpenCode client impersonation -----------------------------------------
// UA is the exact string the OpenCode 1.18.18 CLI emits (AI SDK
// provider-utils 4.0.23 running on Bun 1.3.14); the runtime suffix uses the
// same `getRuntimeEnvironmentUserAgent()` logic, pinned to the impersonated
// client's runtime since this adapter is not the OpenCode binary itself.
const USER_AGENT =
  "opencode/1.18.18 ai-sdk/provider-utils/4.0.23 runtime/bun/1.3.14";
// models.dev is queried with the same identity the fetcher in
// `.github/reasonix-config` uses (a published OpenCode release channel).
const MODELS_DEV_URL = "https://models.dev/api.json";
const MODELS_DEV_USER_AGENT = "opencode/prod/1.18.14/cli";

// OpenCode id.ts state: one counter per millisecond, shared across prefixes.
let lastTimestamp = 0;
let counter = 0;

/**
 * Byte-identical port of OpenCode's `id/create()` (packages/opencode/src/id/id.ts).
 * Encodes `timestamp * 0x1000 + counter` as six big-endian bytes, optionally
 * bitwise-NOTted for "descending" ids, followed by 14 random base62 chars.
 * Session ids use `descending`; message (request) ids use `ascending`.
 */
export function createId(
  prefix: "ses" | "msg",
  direction: "descending" | "ascending",
): string {
  const currentTimestamp = Date.now();
  if (currentTimestamp !== lastTimestamp) {
    lastTimestamp = currentTimestamp;
    counter = 0;
  }
  counter++;
  let now = BigInt(currentTimestamp) * BigInt(0x1000) + BigInt(counter);
  now = direction === "descending" ? ~now : now;
  const timeBytes = Buffer.alloc(6);
  for (let i = 0; i < 6; i++) {
    timeBytes[i] = Number((now >> BigInt(40 - 8 * i)) & BigInt(0xff));
  }
  const chars =
    "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
  const bytes = randomBytes(14); // LENGTH 26 - 12 hex chars
  let suffix = "";
  for (const byte of bytes) suffix += chars[byte % 62];
  return `${prefix}_${timeBytes.toString("hex")}${suffix}`;
}

/** Wire headers of an OpenCode CLI request (anomalyco/opencode request.ts). */
function opencodeHeaders(
  key: string,
  sessionId: string,
  requestId: string,
): Record<string, string> {
  return {
    authorization: `Bearer ${key}`,
    "content-type": "application/json",
    accept: "*/*",
    "accept-encoding": "gzip, deflate, br, zstd",
    "user-agent": USER_AGENT,
    "x-opencode-client": "cli",
    "x-opencode-project": "global",
    "x-opencode-session": sessionId,
    "x-opencode-request": requestId,
  };
}

/** Raw Zen model-list shape (`GET /zen/v1/models`). */
interface ZenModelList {
  data: { id: string }[];
}

/** models.dev entry subset used for per-model capacity metadata. */
interface ModelsDevEntry {
  limit?: { context?: number; output?: number };
  status?: string;
}
interface ModelsDev {
  opencode?: { models?: Record<string, ModelsDevEntry> };
}

let modelsDevCache: Promise<ModelsDev> | undefined;

function fetchModelsDev(): Promise<ModelsDev> {
  modelsDevCache ??= fetch(MODELS_DEV_URL, {
    headers: { "user-agent": MODELS_DEV_USER_AGENT },
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  }).then((response) => {
    if (!response.ok) {
      throw new LlmError(
        `models.dev request failed (HTTP ${response.status})`,
        "TRANSPORT",
      );
    }
    return response.json() as Promise<ModelsDev>;
  });
  return modelsDevCache;
}

/** The same free-model filter as `.github/reasonix-config`'s `get_free_zen_model_ids`. */
function isFreeZenModel(id: string): boolean {
  return id.includes("-free") || id === "big-pickle";
}

// -- Config -----------------------------------------------------------------

/**
 * Plugin config, validated by the same-named schemastery schema. No model
 * data lives here: the catalog is resolved at runtime from the Zen API.
 */
export interface Config {
  /** Credential reference resolved per request; falls back to `public`. */
  apiKeyEnv?: string;
  /** Endpoint base, defaults to the public Zen API. */
  baseURL?: string;
  /** Default model for agents that do not pin one. */
  defaultModel?: string;
  /** Combined context capacity when the model has no exact metadata. */
  defaultContextWindow?: number;
  /** Default per-request output cap. */
  maxTokens?: number;
  /** Deployment thinking policy; `disabled` limits requests to `off`. */
  thinking?: "enabled" | "disabled";
  /** Default reasoning effort. */
  reasoningEffort?: "off" | "low" | "high" | "max";
  /** Maximum provider idle time while one stream read is outstanding. */
  streamIdleTimeoutMs?: number;
}

export const Config: z<Config> = z.object({
  apiKeyEnv: z.string().role("credential-ref").default(DEFAULT_API_KEY_ENV),
  baseURL: z.string().default(PUBLIC_BASE_URL),
  defaultModel: z.string().default(DEFAULT_MODEL),
  defaultContextWindow: z
    .number()
    .step(1)
    .min(1)
    .default(DEFAULT_CONTEXT_WINDOW),
  maxTokens: z.number().step(1).min(1).default(DEFAULT_MAX_TOKENS),
  thinking: z.union(["enabled", "disabled"]),
  reasoningEffort: z.union(["off", "low", "high", "max"]),
  streamIdleTimeoutMs: z
    .number()
    .min(1)
    .default(DEFAULT_STREAM_IDLE_TIMEOUT_MS),
});

/** Resolved, validated connection facts for one operation. */
export interface ResolvedZenOptions {
  apiKeyEnv: CredentialRef;
  baseURL: string;
  defaults: RequestDefaults;
  defaultModel: string;
  defaultContextWindow: number;
  maxTokens: number;
  streamIdleTimeoutMs: number;
}

export function resolveAdapterOptions(config: Config): ResolvedZenOptions {
  return {
    apiKeyEnv: config.apiKeyEnv as CredentialRef,
    baseURL: config.baseURL ?? PUBLIC_BASE_URL,
    defaults: {
      thinking: config.thinking,
      reasoningEffort: config.reasoningEffort,
    },
    defaultModel: config.defaultModel ?? DEFAULT_MODEL,
    defaultContextWindow: config.defaultContextWindow ?? DEFAULT_CONTEXT_WINDOW,
    maxTokens: config.maxTokens ?? DEFAULT_MAX_TOKENS,
    streamIdleTimeoutMs:
      config.streamIdleTimeoutMs ?? DEFAULT_STREAM_IDLE_TIMEOUT_MS,
  };
}

// -- Adapter ----------------------------------------------------------------

const OFF = ReasoningEffortId("off");
const LOW = ReasoningEffortId("low");
const HIGH = ReasoningEffortId("high");
const MAX = ReasoningEffortId("max");
const EFFORTS = [
  { id: OFF, name: "Off" },
  { id: LOW, name: "Low" },
  { id: HIGH, name: "High" },
  { id: MAX, name: "Max" },
] as const;

const OFF_ONLY_EFFORTS = [{ id: OFF, name: "Off" }] as const;

function modelInfo(provider: string, model: string): LlmModelInfo {
  return { provider, id: model, name: model, inputModalities: ["text"] };
}

function httpErrorCode(status: number, message: string): string {
  if (status === 401 || status === 403) return "AUTH";
  const detail = [message, String(status)].join(" ");
  if (isQuotaExceededError(detail) || status === 429)
    return QUOTA_EXCEEDED_CODE;
  if (status === 400 && isContextWindowExceededError(detail))
    return "CONTEXT_WINDOW_EXCEEDED";
  if (status >= 500) return "SERVER";
  return `HTTP_${status}`;
}

/** One instance serves every model; only `stream` is required by the base class. */
export class OpenCodeZenAdapter extends LlmAdapter {
  constructor(
    private readonly hooks: {
      options: () => ResolvedZenOptions;
      resolveApiKey: (connection: ResolvedZenOptions) => Promise<string>;
    },
  ) {
    super();
  }

  override providerInfo(provider: string): LlmProviderInfo {
    return { id: provider, name: "OpenCode Zen" };
  }

  override async listModels(
    provider: string,
  ): Promise<readonly LlmModelInfo[]> {
    const connection = this.hooks.options();
    const apiKey = await this.hooks.resolveApiKey(connection);
    const sessionId = createId("ses", "descending");
    const requestId = createId("msg", "ascending");
    const response = await fetch(`${connection.baseURL}/models`, {
      headers: opencodeHeaders(apiKey, sessionId, requestId),
      signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
    });
    if (!response.ok) {
      throw new LlmError(
        `Zen model list failed (HTTP ${response.status})`,
        "TRANSPORT",
      );
    }
    const list = (await response.json()) as ZenModelList;
    return list.data
      .filter((entry) => isFreeZenModel(entry.id))
      .map((entry) => modelInfo(provider, entry.id))
      .toSorted((left, right) => left.id.localeCompare(right.id));
  }

  override async resolveModel(
    provider: string,
    model: string,
  ): Promise<LlmResolvedModelInfo> {
    const connection = this.hooks.options();
    let contextWindow = connection.defaultContextWindow;
    let maxTokens = connection.maxTokens;
    try {
      const dev = await fetchModelsDev();
      const entry = dev.opencode?.models?.[model];
      const context = entry?.limit?.context;
      const output = entry?.limit?.output;
      if (entry?.status !== "deprecated") {
        if (context !== undefined && context > 0) contextWindow = context;
        if (output !== undefined && output > 0) maxTokens = output;
      }
    } catch {
      // Metadata is advisory; capacity falls back to configured defaults.
    }
    return {
      ...modelInfo(provider, model),
      context: { contextWindow },
      defaultMaxTokens: maxTokens,
      reasoning: {
        efforts:
          connection.defaults.thinking === "disabled"
            ? OFF_ONLY_EFFORTS
            : EFFORTS,
        defaultEffort:
          connection.defaults.reasoningEffort === "off"
            ? OFF
            : connection.defaults.reasoningEffort === "low"
              ? LOW
              : connection.defaults.reasoningEffort === "max"
                ? MAX
                : HIGH,
      },
    };
  }

  override async *stream(options: GenerateOptions): AsyncIterable<StreamChunk> {
    const connection = this.hooks.options();
    const apiKey = await this.hooks.resolveApiKey(connection);
    const consumer = new AbortController();
    const upstream =
      options.signal === undefined
        ? consumer.signal
        : AbortSignal.any([options.signal, consumer.signal]);
    using watchdog = idleWatchdog(
      upstream,
      connection.streamIdleTimeoutMs,
      STREAM_IDLE_TIMEOUT_CODE,
    );
    const payload = JSON.stringify(
      serializeRequest(options, connection.defaults),
    );
    const sessionId = createId("ses", "descending");
    const requestId = createId("msg", "ascending");
    let response: Response;
    try {
      response = await fetch(`${connection.baseURL}/chat/completions`, {
        method: "POST",
        // attributionHeaders() first so the impersonated headers listed after
        // it win for `user-agent`; the user-agent contract of the harness is
        // intentionally subordinated to the OpenCode impersonation here.
        headers: {
          ...attributionHeaders(),
          ...opencodeHeaders(apiKey, sessionId, requestId),
        },
        body: payload,
        signal: upstream,
      });
    } catch (error) {
      if (upstream.aborted) throw error;
      throw new LlmError(
        `Zen API request to ${connection.baseURL} failed`,
        "TRANSPORT",
        { cause: error },
      );
    }

    if (!response.ok) {
      let message = `OpenCode Zen API error (HTTP ${response.status})`;
      try {
        const parsed = (await response.json()) as {
          error?: { message?: string };
        };
        const detail = parsed.error?.message;
        if (detail !== undefined && detail.length > 0) message = detail;
      } catch {
        // The HTTP status still identifies the failure.
      }
      throw new LlmError(message, httpErrorCode(response.status, message), {
        status: response.status,
      });
    }
    if (response.body === null) {
      throw new LlmError("Zen API returned no response body", "EMPTY_RESPONSE");
    }

    const iterator = translate(parseSse(response.body, () => watchdog.pulse()))[
      Symbol.asyncIterator
    ]();
    let exhausted = false;
    try {
      while (true) {
        const result = await watchdog.next(iterator);
        if (result.done) {
          exhausted = true;
          return;
        }
        yield result.value;
      }
    } catch (error: unknown) {
      if (timeoutOf(upstream, STREAM_IDLE_TIMEOUT_CODE) !== undefined) {
        throw new LlmError(
          `Zen stream idle timeout after ${connection.streamIdleTimeoutMs}ms`,
          "TIMEOUT",
          { cause: error },
        );
      }
      if (options.signal?.aborted) {
        throw new LlmError("Zen request aborted by caller", "ABORTED", {
          cause: error,
        });
      }
      if (error instanceof LlmError) throw error;
      throw new LlmError(
        `Zen API stream from ${connection.baseURL} failed`,
        "TRANSPORT",
        { cause: error },
      );
    } finally {
      consumer.abort("Zen stream consumer stopped");
      if (!exhausted && iterator.return !== undefined) {
        try {
          await iterator.return(undefined);
        } catch {
          // The consumer controller already owns termination.
        }
      }
    }
  }
}

// -- Plugin -----------------------------------------------------------------

export function apply(ctx: Context, config: Config): void {
  const options = (): ResolvedZenOptions => resolveAdapterOptions(config);

  const resolveApiKey = async (
    connection: ResolvedZenOptions,
  ): Promise<string> => {
    const ref = connection.apiKeyEnv;
    const credentials = ctx.get("credentials");
    if (credentials !== undefined) {
      const hit = await credentials.resolve(ref);
      if (hit !== undefined) return hit.value;
    }
    const ambient = process.env[ref];
    if (ambient !== undefined && ambient.length > 0) return ambient;
    return PUBLIC_KEY;
  };

  const adapter = new OpenCodeZenAdapter({ options, resolveApiKey });
  ctx.llm.registerAdapter([PROVIDER], adapter);
  // `defaultModel` is advisory metadata for agent creation; the adapter itself
  // accepts any model id the Zen API lists.
  ctx.llm.registerConfigurableProviders([
    {
      provider: PROVIDER,
      displayName: "OpenCode Zen",
      settingsNs: name,
      settingsPath: [],
    },
  ]);
}
