name: ENCODING-BOT
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  workflow_dispatch:
jobs:
  ENCODING-BOT:
    timeout-minutes: 332
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: ${{ github.actor }}/${{ github.workflow }}
          token: ${{ secrets.GH_PAT }}
      - uses: actions/checkout@main
        with:
          repository: ${{ github.actor }}/${{ github.workflow }}.env
          path: ${{ github.workflow }}.env
          token: ${{ secrets.GH_PAT }}
      - run: |
          cp ${{ github.workflow }}.env/.env .env
          rm -rf ${{ github.workflow }}.env
      - uses: actions/cache/restore@main
        id: cache
        with:
          path: bot.db
          key: ${{ github.workflow }}-db-state-${{ github.run_id }}
          restore-keys: ${{ github.workflow }}-db-state-
      - run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq ffmpeg mkvtoolnix
      - run: |
          ./run.sh
          ./run.sh logs
      - if: always()
        run: ./run.sh stop
      - if: always()
        uses: actions/cache/save@main
        with:
          path: bot.db
          key: ${{ github.workflow }}-db-state-${{ github.run_id }}
